import Head from 'next/head'
import React from 'react';
import axios from 'axios';

import Table from '../components/Table';

//@ts-ignore
import styles from '../styles/Home.module.css'

export default function Home() {
  const [appstate, setstate] = React.useState(null);
  const [uploadstate, setupload] = React.useState(0);
  const [csverror, seterror] = React.useState([]);
  const [csvdata, setdata] = React.useState([]);

  function onFileChange(event) {
    setstate( event.target.files[0] );
  };

  async function onFileUpload() {
    if(appstate == null || appstate == undefined)
      return;

    const formData = new FormData();

    formData.append(
      "myFile",
      appstate
    );
    
    setupload(0);

    const config = {
      headers: { 'content-type': 'multipart/form-data' },
      onUploadProgress: (event) => {
        setupload( Math.round((event.loaded * 100) / event.total ));
      },
    };

    const response = await axios.post('http://localhost:3000/api/upload', formData, config);
    if(response.data.error) {
      seterror(response.data.error);
      setdata([]);
      alert('There is an error on the upload CSV');
    }
    else {
      setdata(response.data.data);
      seterror([]);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Task 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Get started by uploading a CSV
        </p>

        <div className={styles.card}>
          <div className={styles.grid}>
            <input type="file" onChange={onFileChange} />
            <br />
            <button onClick={onFileUpload}> Upload!</button>
            <h4>Uploading: {uploadstate}</h4>
          </div>

        </div>

        { csverror.length > 0 &&
          <div>
            <h3 style={{color: 'red'}}> CSV Error </h3>
            { csverror.map((error :string, index :number) => {
              return (
                <p key={index}> {error} </p>
              )
            })
            }
          </div>
        }

      <Table data={csvdata} />
       
      </main>

 
    </div>
  )
}
