import Head from 'next/head'
import React from 'react';
import axios from 'axios';

//@ts-ignore
import styles from '../styles/Home.module.css'

export default function Home() {
  const [appstate, setstate] = React.useState(null);
  const [uploadstate, setupload] = React.useState(0);

  function onFileChange(event) {
    setstate( event.target.files[0] );
  };

  async function onFileUpload() {
    const formData = new FormData();

    formData.append(
      "myFile",
      appstate
    );
    
    setupload(0);

    const config = {
      headers: { 'content-type': 'multipart/form-data' },
      onUploadProgress: (event) => {
        setupload( Math.round((event.loaded * 100) / event.total ));
      },
    };
    await axios.post('http://localhost:3000/api/upload', formData, config);
    
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Task 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Get started by uploading a CSV
        </p>

        <div className={styles.card}>
          <div className={styles.grid}>
            <input type="file" onChange={onFileChange} />
            <br />
            <button onClick={onFileUpload}> Upload!</button>
            <h4>Uploading: {uploadstate}</h4>
          </div>

        </div>
      </main>
    </div>
  )
}
